services:
  apicatalogo:
    image: apicatalogo
    build:
      context: .
      dockerfile: APICatalogo/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ApiCatalogoDB
      MYSQL_USER: luis
      MYSQL_PASSWORD: luis1221
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
